pod 'MKNetworkKit'
pod 'SDWebImage'
pod 'YSLTransitionAnimator'
pod 'LCTabBarController'
pod 'CRNavigationController'
pod 'MMTweenAnimation', :head
pod 'CHTCollectionViewWaterfallLayout'
pod 'SCLAlertView-Objective-C'
pod 'MJRefresh'
pod 'YMSwipeTableViewCell'
pod 'LMPullToBounce'
pod 'IQKeyboardManager'
pod 'ActionSheetPicker-3.0', '~> 2.0.4'
pod 'MXParallaxHeader'
pod 'RMActionController'
pod 'TWPhotoPicker', '~> 1.0.0'
pod 'CNPPopupController'
pod 'IDMPhotoBrowser'
pod 'NYSegmentedControl'